---
  - name: Set up new machine
    hosts: localhost
    become: yes # escalate priviledge
    vars:
      go_version: "1.22.1"
      ansible_user: protopapa
      zsh_dependencies: []

    tasks:
        - name: update and upgrade apt packages
          ansible.builtin.apt:
            upgrade: yes
            update-cache: yes

        - name: apt update
          become: yes
          ansible.builtin.apt:
            update_cache: yes

              #        - name: Add guake terminal repo
              # ansible.builtin.apt_repository:
              # repo: ppa:linuxuprising/guake

              # - name: apt update
              #become: yes
              # ansible.builtin.apt:
              # update_cache: yes

        - name: Install packages basic packages
          ansible.builtin.apt:
            pkg:
              - guake
              - zsh
              - zplug
              - curl
              - unzip
              - vim
              - git 
              - npm
              - scdaemon 
              - ca-certificates
              - gnupg
              - snapd
  
        - name: Create Repositories folder
          ansible.builtin.file:
            path: /home/{{ ansible_user }}/Repositories
            state: directory
            mode: '0755'

  ###### Update npm and install node
  
        - name: Update npm
          ansible.builtin.shell: npm install -g npm

        - name: Install nodejs from nodesource
          become: true
          ansible.builtin.shell: curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -

        - name: Install nodejs
          ansible.builtin.apt:
            pkg: nodejs
              
#### zsh setup

        - name: Ensure Zsh with dependencies are installed
          ansible.builtin.apt:
            name: "{{ ['zsh'] + zsh_dependencies }}"
            state: present
            update_cache: yes
          become: true
        
        - name: Ensure zsh is the default shell
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            shell: "/usr/bin/zsh"
          become: true

        - name: Download Oh My Zsh script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
            dest: /tmp/install_ohmyzsh.sh


        - name: Run Oh My Zsh script
          ansible.builtin.command: sh /tmp/install_ohmyzsh.sh --unattended
          register: ohmyzsh_result
          failed_when: "'FAILED' in ohmyzsh_result.stderr"

#### Install Golang

        - name: download go tar
          ansible.builtin.get_url:
            url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
            dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"

        - name: remove any existing go path
          ansible.builtin.file:
            path: /usr/local/go
            state: absent

        - name: untar go 
          ansible.builtin.unarchive:
            src: /tmp/go{{ go_version }}.linux-amd64.tar.gz
            dest: /usr/local

        - name: add go bin path to path
          ansible.builtin.shell: export PATH=$PATH:/usr/local/go/bin

        - name: add go path to dot profile
          ansible.builtin.lineinfile:
            line: export PATH=$PATH:/usr/local/go/bin
            path: /home/{{ ansible_user }}/.zshrc

        - name: source .zshrc
          ansible.builtin.shell: ". /home/{{ ansible_user }}/.zshrc"
            
#### Install Dropbox

        - name: Install Dropbox from deb
          ansible.builtin.apt:
            deb: "https://www.dropbox.com/download?dl=packages/debian/dropbox_2024.01.22_amd64.deb"

#### Install Docker Engine

        - name: Install Docker
          become: yes
          ansible.builtin.shell:
            cmd: |
              sudo install -m 0755 -d /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              sudo chmod a+r /etc/apt/keyrings/docker.gpg
        
        - name: Add the repository to Apt sources
          block:
            - name: Add repos
              ansible.builtin.shell:
                cmd: |
                  echo \
                  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
                  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
                  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            - name: Update apt
              ansible.builtin.apt:
                upgrade: yes
                update_cache: yes

        - name: Install Docker packages
          become: yes
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: latest
            update_cache: yes

        - name: Ensure Docker group exists
          become: yes
          ansible.builtin.group:
            name: docker
            state: present

        - name: Add User to docker group
          become: yes
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true

### Snap Installations       

        - name: Install packages with snap
          community.general.snap:
            name:
              - goland
              - pycharm-professional
              - hugo 
              - kubectl
              - kontena-lens
              - code
              - slack
              - spotify
            classic: true

